apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: ConfigMap
      name: lab-api-config
    patch: |-
      - op: replace
        path: /data/MEMORY_HOG_MIB
        value: "384"
  - target:
      kind: Deployment
      name: lab-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi
