apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: ConfigMap
      name: lab-api-config
    patch: |-
      - op: replace
        path: /data/STARTUP_DELAY_SECONDS
        value: "45"
  - target:
      kind: Deployment
      name: lab-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/initialDelaySeconds
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/failureThreshold
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/periodSeconds
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/livenessProbe/failureThreshold
        value: 2
