apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: ConfigMap
      name: lab-api-config
    patch: |-
      - op: replace
        path: /data/MODEL_DIR
        value: /app/models/does-not-exist
